# Generated by Django 3.2 on 2022-08-17 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20220817_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskman',
            name='action_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.action'),
        ),
    ]
