# Generated by Django 3.2 on 2022-08-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_taskman_action_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='task',
            field=models.CharField(choices=[(0, 'create'), (1, 'update'), (2, 'delete')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
