# Generated by Django 3.2 on 2022-08-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_action_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='task',
            field=models.IntegerField(choices=[(0, 'create'), (1, 'update'), (2, 'delete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='taskman',
            name='status',
            field=models.BooleanField(choices=[(1, 'COMPLETED'), (0, 'PENDING')], max_length=2),
        ),
    ]
