# Generated by Django 3.2 on 2022-08-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20220817_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskman',
            name='status',
            field=models.CharField(choices=[('C', 'COMPLETED'), ('P', 'PENDING')], max_length=2),
        ),
    ]
