# Generated by Django 3.2 on 2022-08-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_action_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='task',
            field=models.CharField(choices=[(0, 'create'), (1, 'update'), (2, 'delete')], max_length=5000),
        ),
    ]
